### ISSUE TITLE
web accessible?

### ISSUE THREAD

**Issue by craigmulligan** [Agile-IoT/AGILE-Testbed#1]
I'd like to set up integration tests with the sdk as mentioned [here](https://github.com/Agile-IoT/agile-sdk/issues/3). 

To do so I'd need the device to be publicly accessible via http so I could hit the api's from a CI server.

Best way to approach this?

**Comment by aabadie** [comment]
@craig-mulligan, what device are you talking about ? the gateway itself ?
if yes, then you can remotely access the `agile-pi-2` where the full gateway code is installed. See [this documentation](https://github.com/Agile-IoT/AGILE-Testbed#setup).

In a word, the idea is to open a tunnel from your CI server to the API of the device and then point the server to itself (e.g localhost) with the mapped port (ssh -L <server port>:<server hostname>:<remote port> agile-pi-2).

**Comment by craigmulligan** [comment]
Hey @aabadie, 

Yip, I'm talking about the gateway. I'd like for the device to be able to read from devices over BLE too.

Hopefully Travis CI allows ssh tunnels, I'll set up a basic test and ping you if I run in to any trouble. 

Thanks!

**Comment by emmanuelsearch** [comment]
OK. So let me close this issue until further notice. @craig-mulligan if needed at some point, we can re-open it, or open another one.

**Comment by craigmulligan** [comment]
Hey so I got this working locally, the instructions were very clear, thanks!

Now I'm trying to get it working with on travis CI, it's proving to be difficult, I encrypted the key and config file then in the ci server decrypt them and place them in the correct locations, reload the ssh client, add keys ect. but there appears to be a problem with giving travis CI a custom `~/.ssh/config`, as it's unaware of the host aliases. 

I think the easier path forward is to convert the ssh config into a plain bash script, @emmanuelsearch would you be able to help me out with that?

**Comment by craigmulligan** [comment]
Okay, after (a lot) of hacking I got it working, think I've memorised the whole ssh man page 😆

**Comment by aabadie** [comment]
> after (a lot) of hacking I got it working

Great ! Can you give some information about what you did ?

**Comment by craigmulligan** [comment]
I converted the ssh config you have in the instructions into smthing like: 
```
ssh \
-L8080:localhost:8080 -L8000:localhost:8000 \
-L1880:localhost:1880 -L8083:localhost:8083 -L8086:localhost:8086 \
-L3000:localhost:3000 -L2000:localhost:2000 \
<remote-host> -l agile -p <port> -i id_rsa_agile \ 
-t ssh pi@agile-pi-2 \
-L8080:localhost:8080 -L8000:localhost:8000 \
-L1880:localhost:1880 -L8083:localhost:8083 -L8086:localhost:8086 \
-L3000:localhost:3000 -L2000:localhost:2000
```

I then used screen to run it in the background, I tried running the process in the background with `-Nf` or using `nohup` but didn't have any luck there. 

Tests are basic atm but, you can see the full PR here: https://github.com/Agile-IoT/agile-sdk/pull/21/files
